# Generated by Django 4.2.2 on 2023-07-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
