# Generated by Django 4.2.2 on 2023-09-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
